platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

target 'UIBot_Example' do
    use_frameworks!

    target 'UIBot_ExampleUITests' do
        inherit! :search_paths
        pod 'UIBot', :path => '../'
    end

end
